export TEST_EQUIP_CNT=100
export TEST_TAG_PER_EQ=300
export TEST_LOT_PROCESS_TIME=300
export TEST_MAX_ROWCNT=1000000000
export TEST_DATA_TAG_PER_SEC=10
export TEST_TARGET_EPS=0
export TEST_PORT_NO=34000
export TEST_SERVER_IP=127.0.0.1
echo "TEST_EQUIP_CNT : $TEST_EQUIP_CNT"
echo "TEST_TAG_PER_EQ : $TEST_TAG_PER_EQ"
echo "TEST_LOT_PROCESS_TIME : $TEST_LOT_PROCESS_TIME"
echo "TEST_MAX_ROWCNT_TIME : $TEST_MAX_ROWCNT"
echo "TEST_DATA_TAG_PER_SEC : $TEST_DATA_TAG_PER_SEC"
echo "TEST_TARGET_EPS : $TEST_TARGET_EPS"
echo "TEST_PORT_NO : $TEST_PORT_NO"
echo "TEST_SERVER_IP : $TEST_SERVER_IP"

